import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Suspense } from "react";
import "./globals.css";
import Navbar from '@/components/Navbar';
import Footer from '@/components/Footer';
import ConstructionBanner from '@/components/ConstructionBanner';
import NavigationProgress from '@/components/NavigationProgress';


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Suspense fallback={null}>
          <NavigationProgress />
        </Suspense>
        <div className="sticky top-0 z-50 w-full">
          <ConstructionBanner />
          <Navbar />
        </div>
        {children}


        <Footer />
      </body>
    </html>
  );
}
