"""initial

Revision ID: 05b8bc1a37b1
Revises:
Create Date: 2025-11-26 08:45:46.432375

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "05b8bc1a37b1"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "booking", sa.Column("amadeus_order_response", sa.JSON(), nullable=True)
    )
    op.add_column(
        "booking",
        sa.Column("ticket_url", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("booking", "ticket_url")
    op.drop_column("booking", "amadeus_order_response")
    # ### end Alembic commands ###
