"""add_pagination_indexes

Revision ID: f86c6233ffc8
Revises: a1b2c3d4e5f6
Create Date: 2026-01-18 15:31:53.885599

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "f86c6233ffc8"
down_revision: Union[str, Sequence[str], None] = "a1b2c3d4e5f6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index("ix_booking_cursor", "booking", ["created_at", "id"], unique=False)
    op.create_index(
        "ix_booking_user_cursor",
        "booking",
        ["user_id", "created_at", "id"],
        unique=False,
    )
    op.create_index(
        "ix_notification_user_cursor",
        "notification",
        ["user_id", "created_at", "id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_userindb_google_id"), "userindb", ["google_id"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_userindb_google_id"), table_name="userindb")
    op.drop_index("ix_notification_user_cursor", table_name="notification")
    op.drop_index("ix_booking_user_cursor", table_name="booking")
    op.drop_index("ix_booking_cursor", table_name="booking")
    # ### end Alembic commands ###
