"""add notification table

Revision ID: 590f931b45f9
Revises: e91733b854a6
Create Date: 2025-12-18 19:47:30.303740

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "590f931b45f9"
down_revision: Union[str, Sequence[str], None] = "e91733b854a6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("notification", sa.Column("is_read", sa.Boolean(), nullable=False))
    op.drop_index(op.f("ix_notification_id"), table_name="notification")
    op.drop_index(op.f("ix_notification_user_id"), table_name="notification")
    op.create_foreign_key(None, "notification", "userindb", ["user_id"], ["id"])
    op.drop_column("notification", "viewed")
    op.drop_column("notification", "read")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "notification",
        sa.Column("read", sa.BOOLEAN(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "notification",
        sa.Column("viewed", sa.BOOLEAN(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, "notification", type_="foreignkey")
    op.create_index(
        op.f("ix_notification_user_id"), "notification", ["user_id"], unique=False
    )
    op.create_index(op.f("ix_notification_id"), "notification", ["id"], unique=False)
    op.drop_column("notification", "is_read")
    # ### end Alembic commands ###
