"""add total_price field to booking model

Revision ID: e91733b854a6
Revises: f607d4a3ff24
Create Date: 2025-12-09 16:47:52.945878

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "e91733b854a6"
down_revision: Union[str, Sequence[str], None] = "f607d4a3ff24"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "booking",
        sa.Column("total_price", sa.Float(), nullable=False, server_default="0.0"),
    )
    op.alter_column("booking", "total_price", server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("booking", "total_price")
    # ### end Alembic commands ###
