"""add_rbac_permissions_groups

Revision ID: f607d4a3ff24
Revises: 05b8bc1a37b1
Create Date: 2025-12-03 13:05:48.215650

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "f607d4a3ff24"
down_revision: Union[str, Sequence[str], None] = "05b8bc1a37b1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_booking_id"), table_name="booking")
    op.drop_table("booking")
    op.drop_index(op.f("ix_userindb_email"), table_name="userindb")
    op.drop_table("userindb")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "userindb",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("email", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("password", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("reset_token", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column(
            "reset_token_expires",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id", name="userindb_pkey"),
        postgresql_ignore_search_path=False,
    )
    op.create_index(op.f("ix_userindb_email"), "userindb", ["email"], unique=True)
    op.create_table(
        "booking",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("user_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("flight_order_id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("status", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "amadeus_order_response",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("ticket_url", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"], ["userindb.id"], name=op.f("booking_user_id_fkey")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("booking_pkey")),
    )
    op.create_index(op.f("ix_booking_id"), "booking", ["id"], unique=False)
    # ### end Alembic commands ###
